(function(){
  const KEY='rc-body-issues-v1';
  let issues=load();
  const form=document.getElementById('body-issue-form');
  const empty=document.getElementById('body-empty');
  const recencyModel=window.rcSymptomRecencyModel;
  const jointZones=new Set(['shoulder-left','shoulder-right','elbow-left','elbow-right','wrist-left','wrist-right','hip-left','hip-right','knee-left','knee-right','ankle-left','ankle-right','neck']);
  const muscleZones=new Set(['chest','quad-left','quad-right','upper-back','lower-back','glute-left','glute-right','hamstring-left','hamstring-right','calf-left','calf-right']);

  function load(){try{const value=JSON.parse(localStorage.getItem(KEY));return Array.isArray(value)?value:[];}catch(_){return [];}}
  function save(){localStorage.setItem(KEY,JSON.stringify(issues));render();document.dispatchEvent(new CustomEvent('rc:body-issues-updated'));}
  function readingStatus(issue,asOf){return recencyModel.readingStatus(issue,asOf);}
  function latest(issue){return readingStatus(issue).latestPain??(Number(issue.initialPain)||0);}
  function active(){return issues.filter(issue=>issue.status==='active');}
  function formatDate(value){return new Date(value).toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'});}
  function pointFor(issue){return document.querySelector(`.body-point[data-zone="${issue.zone}"]`);}
  function historyBars(issue){const bars=document.createElement('div');bars.className='pain-history';(issue.history||[]).slice(-10).forEach(entry=>{const bar=document.createElement('i');bar.style.setProperty('--pain',entry.pain);bar.dataset.high=entry.pain>=5?'true':'false';bar.title=`${formatDate(entry.date)} · ${entry.pain}/10`;bars.append(bar);});return bars;}
  function issueCard(issue,isArchived){const status=readingStatus(issue);const card=document.createElement('article');card.className=`body-issue-card freshness-${status.freshness}`;const head=document.createElement('div');head.className='body-issue-card-head';const name=document.createElement('div');const type=document.createElement('small');type.textContent=`${issue.type} · ${issue.zoneLabel}`;const description=document.createElement('strong');description.textContent=issue.description;const freshness=document.createElement('span');freshness.className=`body-freshness ${status.tone}`;freshness.textContent=status.label;name.append(type,description,freshness);const pain=document.createElement('span');pain.className=`body-pain${status.requiresUpdate?' stale':''}`;pain.textContent=status.latestPain===null?'—':`${status.requiresUpdate?'ultimo ':''}${status.latestPain}/10`;head.append(name,pain);const detail=document.createElement('p');detail.className='body-issue-description';detail.textContent=issue.notes||'Nessuna nota aggiuntiva.';const meta=document.createElement('div');meta.className='body-issue-meta';const dates=document.createElement('span');dates.textContent=isArchived?`${formatDate(issue.startedAt)} → ${formatDate(issue.resolvedAt)}`:`Ultima valutazione ${status.ageLabel} · affidabilità ${status.confidence==='high'?'alta':status.confidence==='medium'?'media':'bassa'}`;const action=document.createElement('button');action.type='button';action.className='body-issue-action';action.textContent=isArchived?'Riattiva':'Segna risolto';action.addEventListener('click',()=>{issue.status=isArchived?'active':'resolved';if(isArchived)delete issue.resolvedAt;else issue.resolvedAt=new Date().toISOString();save();toast();});meta.append(dates,action);card.append(head,detail,historyBars(issue),meta);return card;}
  function render(){document.querySelectorAll('.body-point').forEach(point=>point.classList.remove('active','high','stale'));const current=active();current.forEach(issue=>{const point=pointFor(issue),status=readingStatus(issue);if(point)point.classList.add('active',...(status.requiresUpdate?['stale']:status.latestPain>=5?['high']:[]));});const activeList=document.getElementById('active-body-issues');activeList.replaceChildren();current.forEach(issue=>activeList.append(issueCard(issue,false)));const archived=issues.filter(issue=>issue.status==='resolved');const archivedList=document.getElementById('archived-body-issues');archivedList.replaceChildren();archived.slice().reverse().forEach(issue=>archivedList.append(issueCard(issue,true)));document.getElementById('archived-issues-count').textContent=String(archived.length);const stale=current.filter(issue=>readingStatus(issue).requiresUpdate).length;document.getElementById('body-active-count').textContent=stale?`${current.length} attivi · ${stale} da aggiornare`:`${current.length} attivi`;}
  function selectZone(button){document.querySelectorAll('.body-point').forEach(point=>point.classList.remove('selected'));button.classList.add('selected');form.reset();form.elements.zone.value=button.dataset.zone;document.getElementById('body-selected-label').textContent=button.dataset.label;form.hidden=false;empty.hidden=true;form.scrollIntoView({behavior:'smooth',block:'nearest'});}
  document.querySelectorAll('.body-point').forEach(button=>{button.classList.add(jointZones.has(button.dataset.zone)?'joint':muscleZones.has(button.dataset.zone)?'muscle':'other');button.addEventListener('click',()=>selectZone(button));});
  const legend=document.createElement('div');legend.className='body-map-legend';legend.innerHTML='<span><i class="region"></i> Area muscolare</span><span><i></i> Articolazione</span>';document.querySelector('.body-maps').append(legend);
  document.getElementById('cancel-body-issue').addEventListener('click',()=>{document.querySelectorAll('.body-point').forEach(point=>point.classList.remove('selected'));form.hidden=true;empty.hidden=false;});
  form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const zone=data.get('zone');const button=document.querySelector(`.body-point[data-zone="${zone}"]`);const duplicate=active().find(issue=>issue.zone===zone);if(duplicate){window.alert('Questa zona è già monitorata. Aggiornala dal check-in giornaliero.');return;}const pain=Number(data.get('pain'));issues.push({id:crypto.randomUUID?crypto.randomUUID():`issue-${Date.now()}`,zone,zoneLabel:button?.dataset.label||zone,type:data.get('type'),description:data.get('description').trim(),notes:data.get('notes').trim(),status:'active',startedAt:new Date().toISOString(),initialPain:pain,history:[{date:new Date().toISOString(),pain,source:'profilo'}]});document.querySelectorAll('.body-point').forEach(point=>point.classList.remove('selected'));form.hidden=true;empty.hidden=false;save();toast();});
  function recordReadings(readings){const now=new Date().toISOString();readings.forEach(reading=>{const issue=issues.find(item=>item.id===reading.id&&item.status==='active');if(issue){if(!Array.isArray(issue.history))issue.history=[];issue.history.push({date:now,pain:Number(reading.pain),source:'check-in'});}});save();}
  window.rcBodyIssues={active:()=>structuredClone(active()),latest,status:readingStatus,recordReadings,all:()=>structuredClone(issues)};
  render();
})();
