(function(){
  'use strict';
  const model=window.rcGoalsModel,coachModel=window.rcRaceCoachModel,eventModel=window.rcEventDemandModel,programmingModel=window.rcEventProgrammingModel,transitionModel=window.rcGoalTransitionModel,store=window.rcDataStore;if(!model||!store)return;
  const form=document.getElementById('goal-form'),modal=document.getElementById('goal-modal'),goalKey=window.rcDataStoreCore?.DATASETS?.goals?.key||'rc-goals-v1';
  let goals=[];
  let coachAuditCollapsed=false;

  function localDate(){const now=new Date();return model.iso(now);}
  function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function safeDataset(name,fallback){try{return store.getDataset(name)??fallback;}catch(_){return fallback;}}
  function read(){try{return store.getDataset('goals')||[];}catch(_){return[];}}
  function sessions(){return window.rcSessions?.getAll?.()||[];}
  function formatDate(key,options={day:'numeric',month:'long',year:'numeric'}){return new Date(`${key}T12:00:00`).toLocaleDateString('it-IT',options);}
  function dateBox(key){const date=new Date(`${key}T12:00:00`);return`<div class="goal-list-item-date"><small>${date.toLocaleDateString('it-IT',{month:'short'}).replace('.','')}</small><strong>${String(date.getDate()).padStart(2,'0')}</strong></div>`;}
  function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
  function goalId(){return`goal-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}
  function toast(message='Obiettivo salvato'){const node=document.getElementById('toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1900);}
  function save(next,reason){store.setDataset('goals',next);goals=read();document.dispatchEvent(new CustomEvent('rc:goals-updated',{detail:{reason}}));render();}
  function ensureInferredGoal(){
    if(localStorage.getItem(goalKey)!==null)return;const inferred=model.inferGoalFromPlan(sessions(),{today:localDate()});if(inferred)save([inferred],'goal-inferred-from-plan');
  }
  function synchronizeGoalDates(){const current=read(),result=model.syncGoalDates(current,sessions());if(!result.changed)return false;store.setDataset('goals',result.goals);goals=result.goals;document.dispatchEvent(new CustomEvent('rc:goals-updated',{detail:{reason:'goal-date-synced-to-race'}}));return true;}
  function synchronizeGoalSessions(){read().filter(goal=>goal.status==='planned').forEach(goal=>window.rcSessions?.syncGoalSession?.(goal));}
  function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
  function toggleResult(){form.querySelector('.goal-result-field').hidden=form.elements.status.value!=='completed';}
  function eventLabel(goal){return eventModel?.variantFor?.(goal)?.label||model.typeLabels[goal?.type]||goal?.type||'Obiettivo';}
  function syncVariantOptions(selected=''){
    const field=document.getElementById('goal-variant-field'),select=form.elements.variant,hint=document.getElementById('goal-variant-hint'),items=eventModel?.variantsFor?.(form.elements.type.value)||[];
    field.hidden=!items.length;select.replaceChildren();hint.textContent='';if(!items.length)return;
    const blank=element('option','','Formato non ancora specificato');blank.value='';select.append(blank);
    items.forEach(item=>{const option=element('option','',item.label);option.value=item.key;select.append(option);});
    const desired=selected||eventModel?.defaultVariantForType?.(form.elements.type.value)||'';
    if(desired&&!items.some(item=>item.key===desired)){const legacy=element('option','',`Formato salvato · ${desired}`);legacy.value=desired;select.append(legacy);}
    select.value=desired;const item=items.find(candidate=>candidate.key===select.value);hint.textContent=item?.formatSummary||'Senza formato il Coach mantiene un profilo generico e a confidenza più bassa.';
  }
  function open(goal=null,registerResult=false){
    form.reset();form.elements.id.value=goal?.id||'';form.elements.name.value=goal?.name||'';form.elements.type.value=goal?.type||'marathon';syncVariantOptions(goal?.variant||'');form.elements.date.value=goal?.date||'';form.elements.priority.value=goal?.priority||'A';form.elements.status.value=registerResult?'completed':goal?.status||'planned';form.elements.target.value=goal?.target||'';form.elements.result.value=goal?.result||'';form.elements.notes.value=goal?.notes||'';
    document.getElementById('goal-form-title').textContent=registerResult?'Registra il risultato':goal?'Modifica obiettivo':'Nuovo obiettivo';document.getElementById('goal-delete').hidden=!goal;toggleResult();modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>form.elements.name.focus(),0);
  }
  function renderSidebar(current){
    const name=document.getElementById('sidebar-goal-name'),summary=document.getElementById('sidebar-goal-summary');if(!current){name.textContent='Nessun obiettivo';summary.textContent='Aggiungi la prossima gara';return;}const days=Math.max(0,model.daysBetween(localDate(),current.date));name.textContent=current.name;summary.textContent=[current.target||null,days===0?'oggi':days===1?'domani':`${days} giorni`].filter(Boolean).join(' · ');
  }
  function renderKeySessions(items){
    const holder=document.getElementById('goal-key-sessions');if(!items.length){holder.innerHTML='<div class="goal-empty-list">Nessuna seduta essenziale futura collegata al piano.</div>';return;}
    holder.innerHTML=items.map(item=>`<div class="goal-list-item">${dateBox(item.date)}<div class="goal-list-item-copy"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.planImport?.phase||model.typeLabels[item.category]||item.category)} · ${item.durationMin} min${Number(item.details?.distanceKm)>0?` · ${Number(item.details.distanceKm)} km`:''}</span></div><span class="goal-priority ${item.priority==='essential'?'A':'B'}">${item.priority==='essential'?'KEY':'IMP'}</span></div>`).join('');
  }
  function renderUpcoming(current,items){
    const holder=document.getElementById('goal-upcoming-list');if(!items.length){holder.innerHTML='<div class="goal-empty-list">Nessun altro appuntamento inserito.</div>';return;}
    const priorityLabel={B:'Gara importante',C:'Gara preparatoria'};
    holder.innerHTML=items.map(item=>`<div class="goal-list-item">${dateBox(item.date)}<div class="goal-list-item-copy"><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(priorityLabel[item.priority]||model.typeLabels[item.type]||'Obiettivo')} · ${escapeHtml(eventLabel(item))}${item.target?` · ${escapeHtml(item.target)}`:''}</span></div><div class="goal-list-actions"><span class="goal-priority ${escapeHtml(item.priority)}">PRIORITÀ ${escapeHtml(item.priority)}</span><button class="goal-list-action" type="button" data-edit-goal="${escapeHtml(item.id)}">Modifica</button></div></div>`).join('');
  }
  function renderAttention(items){
    const panel=document.getElementById('goal-attention-panel'),holder=document.getElementById('goal-attention-list');panel.hidden=!items.length;if(!items.length){holder.replaceChildren();return;}holder.innerHTML=items.map(item=>`<div class="goal-list-item">${dateBox(item.date)}<div class="goal-list-item-copy"><strong>${escapeHtml(item.name)}</strong><span>La gara non viene archiviata finché non registri esplicitamente il risultato.</span></div><button class="primary small" type="button" data-result-goal="${escapeHtml(item.id)}">Registra risultato</button></div>`).join('');
  }
  function renderHistory(items){
    const holder=document.getElementById('goal-history-list');if(!items.length){holder.innerHTML='<div class="goal-empty-list">Lo storico si costruirà dopo la prima gara conclusa.</div>';return;}holder.innerHTML=items.map(item=>`<button class="goal-history-card" type="button" data-edit-goal="${escapeHtml(item.id)}"><span><small>${escapeHtml(formatDate(item.date))} · ${item.status==='cancelled'?'ANNULLATA':'COMPLETATA'}</small><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.target||eventLabel(item))}</span></span><span class="goal-history-result">${escapeHtml(item.result||'Nessun risultato inserito')}</span></button>`).join('');
  }
  function adaptiveSnapshot(allSessions){
    const engine=window.rcAdaptiveEngine;if(!engine)return null;return engine.analyze({today:localDate(),sessions:allSessions,preCheckins:safeDataset('preSessionCheckins',[]),bodyIssues:safeDataset('bodyIssues',[]),whoopCycles:safeDataset('whoopCycles',[]),whoopSleeps:safeDataset('whoopSleeps',[])});
  }
  function coachStat(label,value,note){const node=element('div','goal-coach-stat');node.append(element('small','',label),element('strong','',value),element('span','',note));return node;}
  function renderCoachMethodology(method){
    if(!method)return null;const section=element('section','goal-coach-methodology'),head=element('div','goal-coach-method-head'),copy=element('div');copy.append(element('small','','METODO APPLICATO'),element('strong','',`${method.standard.label} · ${method.standard.version}`));head.append(copy,element('span',`method-confidence ${method.confidence.level}`,method.confidence.label.toUpperCase()));section.append(head);
    const chips=element('div','goal-coach-domain-chips');method.activeDomains.forEach(domain=>chips.append(element('span',`evidence-${domain.evidence}`,`${domain.label} · ${domain.evidence}`)));section.append(chips,element('p','goal-coach-evidence-legend','A = consensus / position stand · B = revisioni sistematiche · C = evidenza specifica limitata'));
    const windows=element('div','goal-coach-windows');method.windows.forEach(item=>{const card=element('div',`goal-coach-window ${item.state}`);card.append(element('strong','',item.label),element('small','',item.purpose),element('span','',item.summary));windows.append(card);});section.append(windows);
    section.append(element('p','goal-coach-window-note','Le finestre numeriche mostrano qui la corsa osservata; check-in, sintomi e WHOOP entrano come segnali separati.'));const details=element('details','goal-coach-method-details'),summary=element('summary','','Principi, limiti e fonti applicate'),body=element('div','goal-coach-method-body'),principles=element('div'),principleList=element('ul');principles.append(element('h3','','Principi attivi'));method.activeDomains.forEach(domain=>principleList.append(element('li','',`${domain.label} — ${domain.principle}`)));principles.append(principleList);
    const sources=element('div'),sourceList=element('ul');sources.append(element('h3','','Riferimenti principali'));method.sources.slice(0,6).forEach(source=>{const item=element('li'),link=element('a','',source.label);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';item.append(link);sourceList.append(item);});sources.append(sourceList);body.append(principles,sources);details.append(summary,body);section.append(details);return section;
  }
  function renderProgrammingPack(goal){
    const pack=programmingModel?.packFor?.(goal);if(!pack)return null;const phase=programmingModel.phaseFor?.(goal,localDate()),section=element('section',`goal-programming-pack ${pack.status}`),head=element('div','goal-programming-head'),copy=element('div'),statusLabel={active:'PACK ATTIVO',contextual:'PRESCRIZIONE CONTESTUALE',pending:'DA REVISIONARE'}[pack.status]||'DA REVISIONARE';
    copy.append(element('small','',`PACK COACH · v${pack.version}`),element('strong','',pack.label),element('p','',phase?`${phase.label} · ${phase.focus}`:pack.guardrail));head.append(copy,element('span',`programming-pack-status ${pack.status}`,statusLabel));section.append(head);
    if(pack.overlay){const overlay=element('div','goal-programming-overlay');overlay.append(element('small','',`FORMATO ${pack.overlay.label.toUpperCase()}${pack.overlay.pro?' · PRO':''}`),element('strong','',pack.overlay.detail),element('span','',pack.overlay.loadDetail));section.append(overlay);}
    const activeSessions=programmingModel.keySessionsFor?.(goal,phase?.key)||[];if(activeSessions.length){const sessions=element('div','goal-programming-sessions');activeSessions.forEach(item=>{const card=element('article');card.append(element('small','',item.role.toUpperCase()),element('strong','',item.label),element('span','',item.detail));sessions.append(card);});section.append(sessions);}
    const details=element('details','goal-programming-details'),summary=element('summary','','Tolleranza, limiti e fonti del pack'),body=element('div','goal-programming-details-body'),checks=element('div'),checkList=element('ul');checks.append(element('h3','','Controlli prima di progredire'));pack.toleranceChecks.forEach(item=>checkList.append(element('li','',item)));checks.append(checkList);
    const limits=element('div'),limitList=element('ul');limits.append(element('h3','','Limiti dichiarati'));pack.limits.forEach(item=>limitList.append(element('li','',item)));limits.append(limitList);
    const evidence=element('div'),sourceList=element('ul');evidence.append(element('h3','','Evidenza applicata'));if(pack.sources.length){pack.sources.forEach(source=>{const item=element('li'),link=element('a','',source.label);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';item.append(link);sourceList.append(item);});evidence.append(sourceList);}else evidence.append(element('p','','Nessuna prescrizione specialistica viene applicata finché il pack non è revisionato.'));
    body.append(checks,limits,evidence);details.append(summary,body);section.append(details,element('small','goal-programming-guardrail',pack.guardrail));return section;
  }
  function renderEventDemands(goal){
    if(!eventModel)return null;const context=eventModel.coordinate({today:localDate(),primary:goal,goals}),profile=context.primary.profile,section=element('section','goal-event-demands'),head=element('div','goal-event-head'),copy=element('div'),confidenceLabel={supported:'RICHIESTE REVISIONATE',contextual:'CONTESTUALE','format-verified':'FORMATO VERIFICATO',generic:'DA CONFERMARE'}[profile.confidence]||'DA CONFERMARE';
    copy.append(element('small','',`RICHIESTE DELL’EVENTO · v${context.version}`),element('strong','',profile.label),element('p','',`${profile.duration.label} · ${profile.disciplines.join(' + ')}`));head.append(copy,element('span',`event-confidence ${profile.confidence}`,confidenceLabel));section.append(head);
    if(profile.formatSummary){const format=element('div','goal-event-format'),formatCopy=element('div');formatCopy.append(element('small','','FORMATO SELEZIONATO'),element('strong','',profile.variant?.label||profile.label),element('span','',profile.formatSummary));format.append(formatCopy,element('b',`programming-status ${profile.programmingStatus}`,profile.programmingStatus==='active'?'PACK COACH ATTIVO':profile.programmingStatus==='demand-reviewed'?'DOMANDE REVISIONATE':profile.programmingStatus==='contextual'?'PRESCRIZIONE CONTESTUALE':'PACK COACH DA REVISIONARE'));section.append(format);}
    const roles=element('div','goal-event-roles');profile.keyRoles.forEach(role=>roles.append(element('span','',role)));section.append(roles);const programmingPack=renderProgrammingPack(goal);if(programmingPack)section.append(programmingPack);
    const demandGrid=element('div','goal-demand-grid'),ordered=context.primary.demands.slice().sort((a,b)=>b.level-a.level||a.label.localeCompare(b.label,'it'));ordered.slice(0,8).forEach(item=>{const card=element('div','goal-demand-item'),label=element('div','goal-demand-label'),track=element('span','goal-demand-track'),fill=element('i');label.append(element('small','',item.label),element('b','',item.levelLabel));track.style.setProperty('--demand-level',item.level);track.setAttribute('role','img');track.setAttribute('aria-label',`${item.label}: ${item.level} su 5, ${item.levelLabel}`);track.append(fill);card.append(label,track);demandGrid.append(card);});section.append(demandGrid);
    const coordination=element('div','goal-coordination'),coordinationHead=element('div','goal-coordination-head');coordinationHead.append(element('div','',undefined),element('span','',context.summary));coordinationHead.firstChild.append(element('small','','COORDINAMENTO A / B / C'),element('strong','','Compatibilità e transizioni'));coordination.append(coordinationHead);
    if(!context.secondary.length)coordination.append(element('div','goal-coordination-empty','Aggiungendo una gara B o C, il Coach confronterà calendario, richieste condivise e costo della transizione.'));
    else{
      const cards=element('div','goal-coordination-list');context.secondary.forEach(item=>{const card=element('article',`goal-coordination-card ${item.tone}`),cardHead=element('div','goal-coordination-card-head'),cardCopy=element('div');cardCopy.append(element('small','',`PRIORITÀ ${item.goal.priority} · ${formatDate(item.goal.date,{day:'numeric',month:'short'})}`),element('strong','',item.goal.name));cardHead.append(cardCopy,element('span','',`${item.overlap.percent}% overlap`));card.append(cardHead,element('h3','',item.title),element('p','',item.summary));if(item.overlap.shared.length){const shared=element('div','goal-coordination-shared');shared.append(element('small','','RICHIESTE CONDIVISE'));item.overlap.shared.forEach(label=>shared.append(element('span','',label)));card.append(shared);}if(item.actions.length){const actions=element('ul');item.actions.forEach(action=>actions.append(element('li','',action)));card.append(actions);}const preview=transitionModel?.previewFor?.(goal,item.goal);if(preview){const timeline=element('div','goal-transition-preview');timeline.append(element('small','','BLOCCO POST-MARATONA'));preview.stages.forEach(stage=>{const step=element('span');step.append(element('b','',stage.label),element('em','',`giorni ${stage.fromDay}–${stage.toDay}`));timeline.append(step);});card.append(timeline);}cards.append(card);});coordination.append(cards);
    }
    section.append(coordination);
    const details=element('details','goal-event-details'),summary=element('summary','','Contratto completo, fonti e limiti'),detailsBody=element('div','goal-event-details-body'),allDemands=element('ul');context.primary.demands.forEach(item=>allDemands.append(element('li','',`${item.label}: ${item.level}/5 · ${item.levelLabel}`)));detailsBody.append(allDemands);
    const sourceBox=element('div');if(profile.sources.length){sourceBox.append(element('h3','','Fonti del pack'));const sourceList=element('ul');profile.sources.forEach(source=>{const item=element('li'),link=element('a','',source.label);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';item.append(link);sourceList.append(item);});sourceBox.append(sourceList);}else sourceBox.append(element('p','','Profilo generico: richiede revisione e conferma prima di diventare prescrittivo.'));detailsBody.append(sourceBox);
    if(profile.formatDetails.length||profile.stations.length){const official=element('div','goal-event-official'),formatList=element('ul');official.append(element('h3','','Dettaglio ufficiale'));profile.formatDetails.forEach(item=>formatList.append(element('li','',item)));if(profile.formatDetails.length)official.append(formatList);if(profile.stations.length){const stations=element('div','goal-event-stations');profile.stations.forEach((station,index)=>{const row=element('div');row.append(element('i','',String(index+1)),element('strong','',station.name),element('span','',[station.work,station.load].filter(Boolean).join(' · ')));stations.append(row);});official.append(stations);}detailsBody.append(official);}
    details.append(summary,detailsBody);section.append(details,element('small','goal-event-guardrail',context.guardrail));return section;
  }
  function renderActiveTransition(transition){
    if(!transition)return null;const section=element('section',`goal-active-transition ${transition.status}`),head=element('div','goal-active-transition-head'),copy=element('div');copy.append(element('small','',`TRANSIZIONE POST-MARATONA · GIORNO +${transition.daysAfter}`),element('strong','',transition.label),element('p','',transition.summary));head.append(copy,element('span','',`${transition.maxSessions} SEDUTE · ≤${transition.maxDurationMin} MIN`));section.append(head);
    const checks=element('div','goal-active-transition-checks');const values=[['Esito gara',transition.signals.resultRecorded],['Fastidi aggiornati',transition.signals.symptomsCurrent],['Dolore compatibile',transition.signals.painClear],['Fatica compatibile',transition.signals.fatigueClear]];values.forEach(([label,passed])=>checks.append(element('span',passed?'passed':'hold',`${passed?'✓':'–'} ${label}`)));section.append(checks,element('small','goal-event-guardrail',transition.guardrail));return section;
  }
  function renderCoachAudit(goal,allSessions){
    const panel=document.getElementById('goal-coach-audit');if(!coachModel){panel.hidden=true;return;}const readiness=adaptiveSnapshot(allSessions),audit=coachModel.audit({today:localDate(),goal,sessions:allSessions,activities:safeDataset('importedActivities',[]),readiness}),planPhase=model.currentPhase(goal,allSessions,localDate());panel.hidden=false;panel.className=`panel goal-coach-audit tone-${audit.assessment.tone}${coachAuditCollapsed?' is-collapsed':''}`;panel.replaceChildren();
    const head=element('div','panel-head'),copy=element('div');copy.append(element('small','',`${audit.methodology?.standard.label.toUpperCase()||'COACH V1'} · AUDIT PREPARAZIONE`),element('h2','',audit.assessment.title));const phase=[`Fase coach: ${audit.phase.label}`,planPhase?.label?`Piano: ${planPhase.label}`:null,audit.pace?`Target: ${audit.pace.label}`:null].filter(Boolean).join(' · ');copy.append(element('p','goal-coach-phase',phase));const headActions=element('div','panel-head-actions'),confidence=element('span',`goal-coach-confidence ${audit.assessment.tone}`,`AFFIDABILITÀ ${audit.confidence.label.toUpperCase()}`),toggle=element('button','panel-collapse-toggle');toggle.type='button';toggle.setAttribute('aria-controls','goal-coach-body');const toggleLabel=element('span','',coachAuditCollapsed?'Apri':'Nascondi'),chevron=element('span','panel-collapse-chevron');chevron.setAttribute('aria-hidden','true');toggle.append(toggleLabel,chevron);const syncToggle=()=>{panel.classList.toggle('is-collapsed',coachAuditCollapsed);toggle.setAttribute('aria-expanded',String(!coachAuditCollapsed));toggle.setAttribute('aria-label',coachAuditCollapsed?'Apri audit del Coach':'Nascondi audit del Coach');toggleLabel.textContent=coachAuditCollapsed?'Apri':'Nascondi';};toggle.addEventListener('click',()=>{coachAuditCollapsed=!coachAuditCollapsed;syncToggle();});syncToggle();headActions.append(confidence,toggle);head.append(copy,headActions);const body=element('div','collapsible-panel-body');body.id='goal-coach-body';const bodyInner=element('div','collapsible-panel-body-inner');bodyInner.append(element('p','goal-coach-summary',audit.assessment.summary));body.append(bodyInner);panel.append(head,body);
    const stats=element('div','goal-coach-grid'),observedValue=audit.observed.kmPerWeek===null?'—':`${audit.observed.kmPerWeek} km/sett`,observedNote=audit.observed.runs?`${audit.observed.runs} ${audit.observed.runs===1?'corsa':'corse'} · ${audit.observed.runFrequency}/sett${audit.observed.longestKm?` · lungo ${audit.observed.longestKm} km`:''}`:'Nessuna distanza osservata',planValue=audit.plan.kmPerWeek===null?'—':`${audit.plan.kmPerWeek} km/sett`,planNote=`${audit.plan.runs} ${audit.plan.runs===1?'corsa allenante':'corse allenanti'}${audit.plan.distancePartial?' · km parziali':''}`,adherenceValue=audit.history.adherence===null?'—':`${Math.round(audit.history.adherence*100)}%`,adherenceNote=audit.history.due?`${audit.history.recorded}/${audit.history.due} ${audit.history.due===1?'esito':'esiti'} · ${audit.history.missing} ${audit.history.missing===1?'mancante':'mancanti'}`:'Nessuna seduta dovuta',specificValue=`${audit.plan.longRuns} ${audit.plan.longRuns===1?'lungo':'lunghi'} · ${audit.plan.quality} qualità`,specificNote=`${audit.plan.strength} forza · ${audit.plan.hyrox} HYROX/Metcon`;
    stats.append(coachStat('BASE OSSERVATA · 28 GG',observedValue,observedNote),coachStat(`PIANO · PROSSIMI ${audit.plan.days} GG`,planValue,planNote),coachStat('ADERENZA OSSERVABILE',adherenceValue,adherenceNote),coachStat('SPECIFICITÀ FUTURA',specificValue,specificNote));bodyInner.append(stats);
    const decision=element('div','goal-coach-decision');decision.append(element('small','','DECISIONE ATTUALE'),element('strong','',audit.assessment.decision));bodyInner.append(decision);const eventDemands=renderEventDemands(goal);if(eventDemands)bodyInner.append(eventDemands);const activeTransition=transitionModel?.assess?.({activeGoal:goal,goals,weekStart:localDate(),sessions:allSessions,analysis:readiness});const transitionPanel=renderActiveTransition(activeTransition);if(transitionPanel)bodyInner.append(transitionPanel);
    const details=element('div','goal-coach-details'),focus=element('div'),evidence=element('div'),focusList=element('ul'),evidenceList=element('ul');focus.append(element('h3','','Focus della fase'),focusList);evidence.append(element('h3','','Perché il coach legge così'),evidenceList);audit.focus.forEach(item=>focusList.append(element('li','',item)));audit.reasons.forEach(item=>evidenceList.append(element('li','',item)));details.append(focus,evidence);bodyInner.append(details);const methodology=renderCoachMethodology(audit.methodology);if(methodology)bodyInner.append(methodology);bodyInner.append(element('small','goal-coach-safety','Questa lettura non modifica il piano. Ogni adattamento resta separato, spiegato, reversibile e richiede conferma. I fastidi vengono monitorati, non diagnosticati.'));
  }
  function render(){
    goals=read();const allSessions=sessions(),classified=model.classifyGoals(goals,localDate()),current=classified.current,dashboard=model.goalDashboard(current,allSessions,localDate());renderSidebar(current);renderAttention(classified.awaitingResult);renderHistory(classified.history);
    document.getElementById('goal-empty').hidden=Boolean(current);document.getElementById('goal-content').hidden=!current;if(!current)return;
    document.getElementById('goal-current-priority').textContent=`PRIORITÀ ${current.priority}`;document.getElementById('goal-current-type').textContent=eventLabel(current).toUpperCase();document.getElementById('goal-current-name').textContent=current.name;document.getElementById('goal-current-target').textContent=current.target||'Nessun target specifico';document.getElementById('goal-countdown-days').textContent=dashboard.days;document.getElementById('goal-countdown-label').textContent=dashboard.days===0?'GARA OGGI':dashboard.days===1?'GIORNO ALLA GARA':'GIORNI ALLA GARA';document.getElementById('goal-current-date').textContent=formatDate(current.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'});document.getElementById('goal-weeks').textContent=dashboard.weeks;
    document.getElementById('goal-phase').textContent=dashboard.phase?.label||'—';document.getElementById('goal-phase-note').textContent=dashboard.phase?(dashboard.phase.source==='coach'?`${dashboard.phase.weekLabel} · Pack Coach`: `Settimana ${dashboard.phase.week} · ${dashboard.phase.weekLabel}`):'Nessuna fase collegata';document.getElementById('goal-week-sessions').textContent=`${dashboard.week.completed}/${dashboard.week.sessions}`;document.getElementById('goal-week-note').textContent=dashboard.week.sessions?'sedute svolte nella settimana':'Nessuna seduta attiva';document.getElementById('goal-week-km').textContent=dashboard.week.plannedKm?`${dashboard.week.plannedKm} km`:'—';document.getElementById('goal-week-km-note').textContent=dashboard.week.distanceKnown?`${dashboard.week.actualKm} km registrati finora`:'distanza prevista dal piano';renderCoachAudit(current,allSessions);renderKeySessions(dashboard.keySessions);renderUpcoming(current,classified.upcoming);
  }

  form.elements.type.addEventListener('change',()=>syncVariantOptions(''));form.elements.variant.addEventListener('change',()=>{const item=eventModel?.variantsFor?.(form.elements.type.value)?.find(candidate=>candidate.key===form.elements.variant.value);document.getElementById('goal-variant-hint').textContent=item?.formatSummary||'Senza formato il Coach mantiene un profilo generico e a confidenza più bassa.';});form.elements.status.addEventListener('change',toggleResult);form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const existing=goals.find(item=>item.id===form.elements.id.value),stamp=new Date().toISOString();const goal={id:existing?.id||goalId(),name:form.elements.name.value.trim(),type:form.elements.type.value,...(form.elements.variant.value?{variant:form.elements.variant.value}:{}),date:form.elements.date.value,dateAuthority:'manual',priority:form.elements.priority.value,status:form.elements.status.value,target:form.elements.target.value.trim(),result:form.elements.status.value==='completed'?form.elements.result.value.trim():'',notes:form.elements.notes.value.trim(),createdAt:existing?.createdAt||stamp,updatedAt:stamp,...(existing?.inferredFromSessionId?{inferredFromSessionId:existing.inferredFromSessionId}:{})};const next=existing?goals.map(item=>item.id===goal.id?goal:item):[...goals,goal];save(next,existing?'goal-updated':'goal-created');if(goal.status==='planned')window.rcSessions?.syncGoalSession?.(goal,{authoritativeDate:true});else window.rcSessions?.removeGoalSession?.(goal.id);close();toast();});
  document.getElementById('goal-delete').addEventListener('click',()=>{const id=form.elements.id.value,goal=goals.find(item=>item.id===id);if(!goal||!window.confirm(`Eliminare “${goal.name}”? L’eventuale seduta calendario creata automaticamente verrà rimossa; una registrazione già compilata resterà nello storico.`))return;window.rcSessions?.removeGoalSession?.(id);save(goals.filter(item=>item.id!==id),'goal-deleted');close();toast('Obiettivo eliminato');});
  document.getElementById('add-goal').addEventListener('click',()=>open());document.getElementById('goal-empty-add').addEventListener('click',()=>open());document.getElementById('edit-current-goal').addEventListener('click',()=>{const current=model.classifyGoals(goals,localDate()).current;if(current)open(current);});document.getElementById('goal-close').addEventListener('click',close);document.getElementById('goal-cancel').addEventListener('click',close);document.getElementById('sidebar-goal').addEventListener('click',()=>window.rcNavigation?.show('goals'));
  document.getElementById('goals').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-goal]'),result=event.target.closest('[data-result-goal]');if(edit){const goal=goals.find(item=>item.id===edit.dataset.editGoal);if(goal)open(goal);}else if(result){const goal=goals.find(item=>item.id===result.dataset.resultGoal);if(goal)open(goal,true);}});
  document.addEventListener('rc:sessions-updated',event=>{if(event.detail?.reason==='excel-plan-imported')ensureInferredGoal();synchronizeGoalDates();render();});document.addEventListener('rc:data-restored',()=>{ensureInferredGoal();synchronizeGoalDates();synchronizeGoalSessions();render();});document.addEventListener('rc:view-changed',event=>{if(event.detail?.view==='goals')render();});['rc:whoop-updated','rc:pre-checkin-updated','rc:body-issues-updated'].forEach(name=>document.addEventListener(name,render));
  window.rcGoals={getAll:()=>structuredClone(goals),open,render};ensureInferredGoal();synchronizeGoalDates();synchronizeGoalSessions();render();setTimeout(render,0);
})();
