(function(){
  'use strict';
  const model=window.rcReconciliationModel;const store=window.rcDataStore;const panel=document.getElementById('reconciliation-panel');if(!model||!store||!panel)return;
  const list=document.getElementById('reconciliation-list');const moreButton=document.getElementById('reconciliation-more');const confirmHighButton=document.getElementById('reconciliation-confirm-high');const history=document.getElementById('reconciliation-history');let visible=6;let current=null;
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const categoryLabels={running:'Corsa',cycling:'Ciclismo',strength:'Forza',hyrox:'HYROX Spec',metcon:'Metcon',test:'Test',recovery:'Recupero',outdoor:'Outdoor',other:'Altro'};
  const formatDate=key=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(String(key||'')))return'—';const [year,month,day]=key.split('-').map(Number);return new Date(year,month-1,day).toLocaleDateString('it-IT',{weekday:'short',day:'numeric',month:'short',year:'numeric'});};
  const formatDuration=minutes=>{const value=Math.round(Number(minutes));if(!Number.isFinite(value)||value<=0)return'Durata n/d';const hours=Math.floor(value/60);const rest=value%60;return hours?`${hours} h${rest?` ${rest} min`:''}`:`${rest} min`;};
  const timePart=value=>{const match=/T(\d{2}):(\d{2})/.exec(String(value||''));return match?`${match[1]}:${match[2]}`:null;};
  const confidenceText=candidate=>`${candidate.confidenceLabel==='high'?'Alta':candidate.confidenceLabel==='medium'?'Media':'Bassa'} · ${Math.round(candidate.confidence*100)}%`;
  const showToast=message=>{const toast=document.getElementById('toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);};
  function sourceCard(kind,item){
    if(!item)return'';const config={strava:{label:'STRAVA',className:'strava',name:item.name||'Attività Strava',meta:[categoryLabels[item.category]||item.category,formatDuration((Number(item.movingSec)||Number(item.elapsedSec))/60),timePart(item.localStart)?`${timePart(item.localStart)} · orario export`:null]},whoop:{label:'WHOOP',className:'whoop',name:item.name||'Allenamento WHOOP',meta:[categoryLabels[item.category]||item.category,formatDuration(item.durationMin),timePart(item.start)?`${timePart(item.start)} · ${item.timezone||'ora locale'}`:null]},plan:{label:'PIANO',className:'plan',name:item.title||'Seduta del piano',meta:[categoryLabels[item.category]||item.category,formatDuration(item.durationMin),item.outcome?'Esito già registrato':'Esito non compilato']}}[kind];
    return`<div class="reconciliation-source ${config.className}"><span>${config.label}</span><strong>${escapeHtml(config.name)}</strong><small>${config.meta.filter(Boolean).map(escapeHtml).join(' · ')}</small></div>`;
  }
  function candidateCard(candidate){
    const count=Number(Boolean(candidate.strava))+Number(Boolean(candidate.whoop))+Number(Boolean(candidate.session)),recorded=Boolean(candidate.session?.outcome);const heading=recorded?'Aggiungi i dati dispositivo alla seduta registrata':`${count===3?'Tre':'Due'} registrazioni compatibili`;const note=recorded?'<p class="reconciliation-recorded-note">La tua registrazione manuale resta il dato principale: l’abbinamento aggiunge soltanto FC, strain, durata e altre misure disponibili.</p>':'';
    return`<article class="reconciliation-card${recorded?' recorded':''}" data-reconciliation-card="${escapeHtml(candidate.id)}"><div class="reconciliation-card-head"><div><small>${escapeHtml(formatDate(candidate.date))}</small><strong>${heading}</strong></div><span class="reconciliation-confidence ${candidate.confidenceLabel}">${escapeHtml(confidenceText(candidate))}</span></div><div class="reconciliation-sources">${sourceCard('strava',candidate.strava)}${sourceCard('whoop',candidate.whoop)}${sourceCard('plan',candidate.session)}</div>${note}<div class="reconciliation-reasons">${candidate.reasons.map(reason=>`<span>✓ ${escapeHtml(reason)}</span>`).join('')}</div><div class="reconciliation-actions"><button class="ghost" type="button" data-reconciliation-dismiss="${escapeHtml(candidate.id)}">Non coincidono</button><button class="primary" type="button" data-reconciliation-confirm="${escapeHtml(candidate.id)}">${recorded?'Collega i dati':'Conferma abbinamento'}</button></div></article>`;
  }
  function decisionSources(decision,maps){
    const names=[];if(decision.stravaActivityId)names.push(`Strava: ${maps.strava.get(decision.stravaActivityId)?.name||'attività non più disponibile'}`);if(decision.whoopWorkoutId)names.push(`WHOOP: ${maps.whoop.get(decision.whoopWorkoutId)?.name||'allenamento non più disponibile'}`);if(decision.sessionId)names.push(`Piano: ${maps.sessions.get(decision.sessionId)?.title||'seduta non più disponibile'}`);return names;
  }
  function historyItem(decision,maps){const confirmed=decision.status==='confirmed';const sources=decisionSources(decision,maps);return`<div class="reconciliation-history-item"><div><span class="reconciliation-history-status ${confirmed?'confirmed':'dismissed'}">${confirmed?'CONFERMATO':'ESCLUSO'}</span><strong>${escapeHtml(formatDate(decision.date))}</strong><small>${sources.map(escapeHtml).join(' · ')}</small></div><button class="ghost" type="button" data-reconciliation-remove="${escapeHtml(decision.id)}">${confirmed?'Annulla abbinamento':'Riconsidera'}</button></div>`;}
  function emptyMessage(state,counts){
    if(!counts.strava&&!counts.whoop)return'Importa Strava e WHOOP: qui confronteremo le registrazioni senza duplicare gli allenamenti.';
    if(!counts.strava){const unmatched=state.stats.unmatchedWhoop;return unmatched?`${unmatched} ${unmatched===1?'workout WHOOP resta salvato':'workout WHOOP restano salvati'} senza abbinamento: nessun dato è perso, ma il confronto col Piano non è ancora abbastanza affidabile. Strava è facoltativo e può migliorare il riconoscimento.`:'WHOOP è disponibile. Le attività compatibili con il Piano appariranno qui anche senza Strava.';}
    if(!counts.whoop)return'Strava è disponibile. Importa WHOOP per confrontare gli allenamenti registrati.';
    if(state.confirmed.length)return'Tutte le proposte disponibili sono state revisionate.';
    return'Non sono stati trovati abbinamenti sufficientemente affidabili. Le fonti restano separate e nessun dato viene eliminato.';
  }
  function readState(){const stravaActivities=store.getDataset('importedActivities');const whoopWorkouts=store.getDataset('whoopWorkouts');const sessions=store.getDataset('sessions');const decisions=store.getDataset('reconciliationDecisions');return{state:model.buildReconciliationState({stravaActivities,whoopWorkouts,sessions,decisions}),stravaActivities,whoopWorkouts,sessions,decisions};}
  function render(){
    try{current=readState();}catch(error){list.innerHTML=`<div class="reconciliation-empty error">${escapeHtml(error.message||'Dati non leggibili.')}</div>`;confirmHighButton.hidden=true;moreButton.hidden=true;return;}
    const {state,stravaActivities,whoopWorkouts,sessions,decisions}=current;const high=state.suggestions.filter(item=>item.confidenceLabel==='high');document.getElementById('reconciliation-pending').textContent=state.stats.suggestions;document.getElementById('reconciliation-confirmed').textContent=state.stats.confirmed;document.getElementById('reconciliation-unmatched-strava').textContent=state.stats.unmatchedStrava;document.getElementById('reconciliation-unmatched-whoop').textContent=state.stats.unmatchedWhoop;
    document.getElementById('reconciliation-status').textContent=state.suggestions.length?`${state.suggestions.length} ${state.suggestions.length===1?'proposta costruita':'proposte costruite'} da orario, disciplina e durata. ${state.suggestions.length===1?'Controllala prima di usarla':'Controllale prima di usarle'} come un’unica seduta.`:emptyMessage(state,{strava:stravaActivities.length,whoop:whoopWorkouts.length});
    confirmHighButton.hidden=!high.length;confirmHighButton.textContent=high.length===1?'Conferma 1 proposta ad alta affidabilità':`Conferma ${high.length} proposte ad alta affidabilità`;
    list.innerHTML=state.suggestions.length?state.suggestions.slice(0,visible).map(candidateCard).join(''):`<div class="reconciliation-empty">${escapeHtml(emptyMessage(state,{strava:stravaActivities.length,whoop:whoopWorkouts.length}))}</div>`;
    moreButton.hidden=state.suggestions.length<=6;moreButton.style.display=moreButton.hidden?'none':'block';moreButton.textContent=visible>=state.suggestions.length?'Mostra meno':`Mostra altri ${state.suggestions.length-visible} abbinamenti`;
    const maps={strava:new Map(stravaActivities.map(item=>[item.id,item])),whoop:new Map(whoopWorkouts.map(item=>[item.id,item])),sessions:new Map(sessions.map(item=>[item.id,item]))};const ordered=[...decisions].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));document.getElementById('reconciliation-history-count').textContent=ordered.length;document.getElementById('reconciliation-history-list').innerHTML=ordered.length?ordered.map(item=>historyItem(item,maps)).join(''):'<div class="reconciliation-history-empty">Nessuna decisione registrata.</div>';history.hidden=!ordered.length;
  }
  function findCandidate(id){return current?.state.suggestions.find(item=>item.id===id)||null;}
  function notify(reason){document.dispatchEvent(new CustomEvent('rc:reconciliation-updated',{detail:{reason}}));render();}
  function saveCandidate(id,status){const candidate=findCandidate(id);if(!candidate)return;try{store.saveReconciliationDecision(model.createReconciliationDecision(candidate,status,new Date()));notify(status==='confirmed'?'reconciliation-confirmed':'reconciliation-dismissed');showToast(status==='confirmed'?'Abbinamento confermato':'Proposta esclusa');}catch(error){window.alert(error.message||'Non è stato possibile salvare la decisione.');}}
  panel.addEventListener('click',event=>{const confirmButton=event.target.closest('[data-reconciliation-confirm]');if(confirmButton){saveCandidate(confirmButton.dataset.reconciliationConfirm,'confirmed');return;}const dismissButton=event.target.closest('[data-reconciliation-dismiss]');if(dismissButton){saveCandidate(dismissButton.dataset.reconciliationDismiss,'dismissed');return;}const removeButton=event.target.closest('[data-reconciliation-remove]');if(removeButton){try{store.removeReconciliationDecision(removeButton.dataset.reconciliationRemove);notify('reconciliation-removed');showToast('Decisione annullata');}catch(error){window.alert(error.message||'Non è stato possibile annullare la decisione.');}}});
  confirmHighButton.addEventListener('click',()=>{const high=current?.state.suggestions.filter(item=>item.confidenceLabel==='high')||[];if(!high.length)return;if(!window.confirm(`Confermare ${high.length} ${high.length===1?'abbinamento ad alta affidabilità':'abbinamenti ad alta affidabilità'}?\n\nLe registrazioni verranno collegate, ma nessuna seduta del piano sarà segnata automaticamente come svolta.`))return;try{store.saveReconciliationDecisions(high.map(candidate=>model.createReconciliationDecision(candidate,'confirmed',new Date())));notify('reconciliation-confirmed-bulk');showToast(`${high.length} ${high.length===1?'abbinamento confermato':'abbinamenti confermati'}`);}catch(error){window.alert(error.message||'Non è stato possibile salvare gli abbinamenti.');}});
  moreButton.addEventListener('click',()=>{visible=visible>=current.state.suggestions.length?6:current.state.suggestions.length;render();});window.addEventListener('rc:data-restored',render);document.addEventListener('rc:sessions-updated',render);document.addEventListener('rc:whoop-updated',render);document.addEventListener('rc:view-changed',event=>{if(event.detail?.view==='data')render();});render();
})();
