(function(){
  const root=document.getElementById('workout-page');if(!root||!window.rcWorkoutModeModel)return;
  const modelApi=window.rcWorkoutModeModel;
  let selectedId=null,timerSeconds=0,timerRemaining=0,timerEndAt=null,timerInterval=null,timerSignature='';

  function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function localDate(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
  function current(){return modelApi.buildWorkoutDay({today:localDate(),sessions:window.rcSessions?.getAll?.()||[],preCheckins:window.rcCheckins?.getHistory?.()||[],selectedId});}
  function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'});}
  function button(label,className,handler){const node=element('button',className,label);node.type='button';node.addEventListener('click',handler);return node;}
  function targetChip(target,className='workout-target'){
    const chip=element('span',className);const color=window.rcTrainingZonesModel?.zoneColor?.(target.zone,'hr');
    if(color){chip.classList.add('has-zone');chip.style.setProperty('--zone-color',color);}
    chip.append(element('small','',target.label),element('strong','',target.value));return chip;
  }
  const anatomyPositions={
    chest:['front',50,58,17,10],abdomen:['front',50,84,12,17],'shoulder-left':['front',70,48,7,6],'shoulder-right':['front',30,48,7,6],'upper-arm-left':['front',78,68,5,12],'upper-arm-right':['front',22,68,5,12],'forearm-left':['front',83,93,4,13],'forearm-right':['front',17,93,4,13],'quad-left':['front',59,145,8,22],'quad-right':['front',41,145,8,22],'adductor-left':['front',54,137,4,19],'adductor-right':['front',46,137,4,19],'shin-left':['front',59,184,5,19],'shin-right':['front',41,184,5,19],
    'upper-back':['back',50,59,18,14],'lower-back':['back',50,88,13,15],'triceps-left':['back',78,68,5,12],'triceps-right':['back',22,68,5,12],'glute-left':['back',59,116,9,11],'glute-right':['back',41,116,9,11],'hamstring-left':['back',59,148,7,22],'hamstring-right':['back',41,148,7,22],'calf-left':['back',59,184,6,17],'calf-right':['back',41,184,6,17]
  };
  function anatomyFigure(view,stimulus){
    const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('strength-anatomy-figure');svg.setAttribute('viewBox','0 0 100 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',view==='front'?'Distretti allenati, vista anteriore':'Distretti allenati, vista posteriore');
    svg.innerHTML='<g class="strength-anatomy-base"><ellipse cx="50" cy="16" rx="10" ry="13"/><path d="M42 29h16l2 10-10 7-10-7z"/><path d="M32 39q18-9 36 0c6 15 6 48-1 68H33c-7-20-7-53-1-68z"/><path d="M32 42Q20 45 17 58L8 105q-1 7 5 8 5 1 7-8l13-47zM68 42q12 3 15 16l9 47q1 7-5 8-5 1-7-8L67 58z"/><path d="M35 104h30l6 16-8 18H37l-8-18z"/><path d="M39 134c-4 18-5 43-3 60l2 20h11l1-42v-38zM61 134c4 18 5 43 3 60l-2 20H51l-1-42v-38z"/></g>';
    const primary=new Set(stimulus?.primaryRegions||[]),secondary=new Set(stimulus?.secondaryRegions||[]);[...secondary,...primary].forEach(zone=>{const point=anatomyPositions[zone];if(!point||point[0]!==view)return;const marker=document.createElementNS('http://www.w3.org/2000/svg','ellipse');marker.setAttribute('cx',point[1]);marker.setAttribute('cy',point[2]);marker.setAttribute('rx',point[3]);marker.setAttribute('ry',point[4]);marker.setAttribute('class',primary.has(zone)?'primary':'secondary');svg.append(marker);});return svg;
  }
  function renderStrengthOverview(session){
    const stimulus=session.strengthStimulus;if(!stimulus?.recognized)return null;const card=element('article','strength-session-overview');const head=element('div','strength-overview-head');const copy=element('div');copy.append(element('small','',session.performed?'STIMOLO REGISTRATO':'ANTEPRIMA ANATOMICA'),element('h3','',session.performed?'Distretti delle serie principali':'Distretti coinvolti'));head.append(copy,element('span','',`${stimulus.recognized}/${stimulus.total} esercizi mappati`));const content=element('div','strength-overview-content');const maps=element('div','strength-anatomy-pair');const front=element('div','strength-anatomy-view');front.append(anatomyFigure('front',stimulus),element('small','','ANTERIORE'));const back=element('div','strength-anatomy-view');back.append(anatomyFigure('back',stimulus),element('small','','POSTERIORE'));maps.append(front,back);const detail=element('div','strength-stimulus-detail');const patterns=element('div','strength-stimulus-chips');stimulus.patterns.forEach(value=>patterns.append(element('span','pattern',value)));const muscles=element('p','',`Primari: ${stimulus.primaryMuscles.join(', ')}`);detail.append(patterns,muscles);if(stimulus.unknown.length)detail.append(element('small','strength-stimulus-unknown',`${stimulus.unknown.length} esercizi personalizzati non hanno ancora una mappatura.`));content.append(maps,detail);card.append(head,content);return card;
  }
  function renderStrengthReview(review){
    if(!review?.rows?.length)return null;const card=element('article','strength-session-review');const head=element('div','strength-review-head');const copy=element('div');copy.append(element('small','','REVIEW FORZA'),element('h3','','Programma e serie registrate'));head.append(copy,element('span','',`${review.matched}/${review.planned} previsti${review.added?` · ${review.added} aggiunti`:''}`));const rows=element('div','strength-review-rows');review.rows.forEach(item=>{const row=element('div',`strength-review-row ${item.status}`);const name=element('div','strength-review-name');name.append(element('strong','',item.name),element('small','',item.meta?.patternLabel||'Esercizio personalizzato'));const planned=element('div','strength-review-metric');planned.append(element('small','','PROGRAMMATO'),element('span','',item.planned));const actual=element('div','strength-review-metric');actual.append(element('small','','SVOLTO'),element('span','',item.actual));const state=element('span',`strength-review-state ${item.status}`,item.status==='recorded'?(!item.volumeKnown?'Volume n.d.':item.plannedSets&&item.actualSets!==item.plannedSets?`${item.actualSets}/${item.plannedSets} serie`:'Registrato'):item.status==='added'?'Aggiunto':'Non registrato');row.append(name,planned,actual,state);rows.append(row);});card.append(head,rows,element('p','strength-review-note',review.volumeKnown?'Il Coach confronta il numero di serie svolte con quelle programmate; per l’e1RM seleziona automaticamente la migliore serie valida.':'Registrazione precedente alla v67: la migliore serie resta valida per l’e1RM, ma il volume totale non è disponibile.'));return card;
  }
  function sessionSwitcher(model){
    if(model.sessions.length<2)return null;const wrap=element('div','workout-switcher');wrap.append(element('small','','SEDUTE DI OGGI'));
    const choices=element('div','workout-switcher-choices');model.sessions.forEach(item=>{const choice=button(item.title,`workout-switch${item.id===model.selected.id?' active':''}`,()=>{selectedId=item.id;resetTimerFor(item);render();});choice.setAttribute('aria-pressed',String(item.id===model.selected.id));const dot=element('i',item.meta.css);choice.prepend(dot);choices.append(choice);});wrap.append(choices);return wrap;
  }
  function renderBlock(block,index){
    const phase=block.phase?` phase-${block.phase}`:'';const card=element('article',`workout-block ${block.kind||'segment'}${phase}${block.intensity?` intensity-${block.intensity}`:''}${block.actual?' actual':''}`);const top=element('div','workout-block-top');const count=element('span','workout-block-number',String(index+1).padStart(2,'0'));const copy=element('div');copy.append(element('small','',block.actual?'ESEGUITO':block.eyebrow||'BLOCCO'),element('h3','',block.title||'Blocco'));top.append(count,copy);card.append(top);
    if(block.kind==='exercise'){const metrics=element('div','workout-exercise-metrics');(block.metrics||[]).forEach(value=>metrics.append(element('span','',value)));card.append(metrics);if(block.exerciseMeta){const meta=element('div','workout-exercise-profile');meta.append(element('strong','',block.exerciseMeta.patternLabel),element('span','',block.exerciseMeta.primaryMuscles.join(' · ')),element('small','',block.exerciseMeta.equipment.join(' · ')));card.append(meta);}}
    else if(block.kind==='repeat'){const steps=element('div','workout-repeat-steps');(block.steps||[]).forEach((step,stepIndex)=>{const row=element('div',`workout-step phase-${step.phase||'free'} intensity-${step.intensity||'easy'}`);const label=element('div','workout-step-label');label.append(element('b','',String(stepIndex+1)),element('span','',step.title));const duration=element('div','workout-step-duration');duration.append(element('small','','DURATA'),element('strong','',step.duration||step.value));const targets=element('div','workout-step-targets');(step.targets||[]).forEach(target=>targets.append(targetChip(target)));row.append(label,duration,targets);steps.append(row);});card.append(steps);}
    else if(block.duration){const performance=element('div','workout-block-performance');const duration=element('div','workout-block-duration');duration.append(element('small','','DURATA'),element('strong','',block.duration));const targets=element('div','workout-targets');(block.targets||[]).forEach(target=>targets.append(targetChip(target)));performance.append(duration,targets);card.append(performance);}
    else card.append(element('p','',block.value||'Indicazioni da definire'));
    if(block.rest){const rest=element('button','workout-rest-shortcut',`⏱ ${block.rest}`);rest.type='button';rest.addEventListener('click',()=>{const seconds=modelApi.parseRestSeconds(block.rest);if(seconds){setTimer(seconds);startTimer();document.getElementById('workout-timer')?.scrollIntoView({behavior:'smooth',block:'center'});}});card.append(rest);}
    return card;
  }
  function timerLabel(){const value=document.getElementById('workout-timer-value');if(value)value.textContent=modelApi.formatTimer(timerRemaining);const toggle=document.getElementById('workout-timer-toggle');if(toggle)toggle.textContent=timerEndAt?'Pausa':'Avvia';}
  function stopTicker(){if(timerInterval){clearInterval(timerInterval);timerInterval=null;}}
  function tick(){
    if(!timerEndAt)return;timerRemaining=Math.max(0,Math.ceil((timerEndAt-Date.now())/1000));timerLabel();
    if(timerRemaining===0){timerEndAt=null;stopTicker();timerLabel();document.getElementById('workout-timer')?.classList.add('finished');setTimeout(()=>document.getElementById('workout-timer')?.classList.remove('finished'),900);if(navigator.vibrate)navigator.vibrate([120,80,120]);}
  }
  function setTimer(seconds){timerEndAt=null;stopTicker();timerSeconds=seconds;timerRemaining=seconds;document.querySelectorAll('.workout-timer-preset').forEach(item=>item.classList.toggle('active',Number(item.dataset.seconds)===seconds));timerLabel();}
  function startTimer(){if(timerEndAt){timerRemaining=Math.max(0,Math.ceil((timerEndAt-Date.now())/1000));timerEndAt=null;stopTicker();timerLabel();return;}if(timerRemaining<=0)timerRemaining=timerSeconds;timerEndAt=Date.now()+timerRemaining*1000;timerInterval=setInterval(tick,250);timerLabel();}
  function resetTimer(){setTimer(timerSeconds);}
  function timerConfig(session){return modelApi.timerConfig?.(session)||null;}
  function resetTimerFor(session){const config=timerConfig(session),seconds=config?.presets?.[0]?.seconds||0;timerSignature=config?`${session.id}:${config.presets.map(item=>item.seconds).join(',')}`:'';if(seconds)setTimer(seconds);else{timerEndAt=null;stopTicker();timerSeconds=0;timerRemaining=0;}}
  function renderTimer(session){
    const config=timerConfig(session);if(!config?.presets?.length)return null;
    const card=element('aside','workout-timer-card');card.id='workout-timer';card.append(element('small','',config.title),element('strong','workout-timer-value',modelApi.formatTimer(timerRemaining)));card.querySelector('strong').id='workout-timer-value';
    const presets=element('div',`workout-timer-presets${config.presets.length===1?' single':''}`);config.presets.forEach(item=>{const preset=button(item.label,'workout-timer-preset',()=>setTimer(item.seconds));preset.dataset.seconds=item.seconds;preset.classList.toggle('active',item.seconds===timerSeconds);presets.append(preset);});
    const controls=element('div','workout-timer-controls');const toggle=button(timerEndAt?'Pausa':'Avvia','primary',startTimer);toggle.id='workout-timer-toggle';controls.append(toggle,button('Reset','ghost',resetTimer));card.append(presets,controls,element('p','',`${config.note} Il timer si riallinea se l’app viene sospesa.`));return card;
  }
  function renderRest(model){
    timerEndAt=null;stopTicker();root.className='workout-page rest-day';const card=element('article','workout-rest-card');const mark=element('div','workout-rest-mark','REST');const copy=element('div');copy.append(element('small','','OGGI'),element('h2','','Rest day'),element('p','',model.next?`Prossima seduta: ${model.next.title} · ${formatDate(model.next.date)}.`:'Nessuna seduta programmata. Puoi aggiornare il piano quando vuoi.'));card.append(mark,copy,button(model.next?'Apri il piano':'Programma la settimana','primary',()=>window.rcNavigation?.show('plan')));root.replaceChildren(card);
  }
  function renderSession(model){
    const session=model.selected;root.className=`workout-page category-${session.meta.css}`;const switcher=sessionSwitcher(model);const hero=element('article','workout-hero');const copy=element('div','workout-hero-copy');const eyebrow=element('div','workout-hero-eyebrow');eyebrow.append(element('span',`workout-category ${session.meta.css}`,session.meta.kicker),element('span',`workout-status ${session.state.css}`,session.state.label));copy.append(eyebrow,element('h2','',session.title),element('p','',session.notes||`${session.meta.label} · ${session.priorityLabel}`));const metrics=element('div','workout-hero-metrics');[[session.timeRange,'ORARIO'],[session.displayDuration,'DURATA'],[session.priorityLabel.toUpperCase(),'PRIORITÀ']].forEach(([value,label])=>{const item=element('span');item.append(element('small','',label),element('strong','',value));metrics.append(item);});hero.append(copy,metrics);
    const layout=element('div','workout-layout');const main=element('section','workout-main');const head=element('div','workout-section-head');head.append(element('div','',''),element('span','',''));head.firstChild.append(element('small','','SESSIONE'),element('h2','',session.performed?'Quello che hai svolto':'Cosa fare oggi'));head.lastChild.textContent=`${session.blocks.length} ${session.blocks.length===1?'blocco':'blocchi'}`;main.append(head);const overview=renderStrengthOverview(session);if(overview)main.append(overview);const list=element('div','workout-blocks');session.blocks.forEach((block,index)=>list.append(renderBlock(block,index)));main.append(list);const strengthReview=session.performed?renderStrengthReview(session.strengthReview):null;if(strengthReview)main.append(strengthReview);
    if(session.details?.accessoryNotes||session.details?.complementaryNotes||session.notes){const notes=element('article','workout-notes');notes.append(element('small','','NOTE'),element('p','',session.details?.accessoryNotes||session.details?.complementaryNotes||session.notes));main.append(notes);}
    const rail=element('div','workout-rail'),timer=renderTimer(session);if(timer)rail.append(timer);else rail.classList.add('timer-hidden');const actions=element('article','workout-actions-card');actions.append(element('small','',session.performed?'REGISTRAZIONE':'SESSIONE'),element('h3','',session.performed?'Seduta registrata':session.preCheckin?'Check-in completato':'Quando sei pronto'));
    if(session.performed||session.outcome)actions.append(button('Apri registrazione','primary',()=>window.rcSessions?.openOutcome?.(session.id)));
    else{actions.append(button('Registra seduta','primary',()=>window.rcSessions?.openOutcome?.(session.id)));actions.append(button(session.preCheckin?'Modifica check-in':'Check-in pre sessione',session.preCheckin?'workout-link':'ghost',()=>window.rcCheckins?.openPre?.(session.id)));}
    actions.append(button('Modifica programmazione','workout-link',()=>window.rcSessions?.openEditor?.(session.id)));rail.append(actions);layout.append(main,rail);root.replaceChildren(...(switcher?[switcher]:[]),hero,layout);timerLabel();
  }
  function render(){const model=current();if(!model.selected){selectedId=null;timerSignature='';renderRest(model);return;}selectedId=model.selected.id;const config=timerConfig(model.selected),signature=config?`${model.selected.id}:${config.presets.map(item=>item.seconds).join(',')}`:'';if(signature!==timerSignature)resetTimerFor(model.selected);renderSession(model);}

  ['rc:sessions-updated','rc:data-restored','rc:pre-checkin-updated'].forEach(name=>document.addEventListener(name,render));
  document.addEventListener('rc:view-changed',event=>{if(event.detail?.view==='workout')render();});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
  render();
})();
